CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Conversations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id")
);

CREATE TABLE "Profiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Mail" text NOT NULL,
    "UniqueNotificationToken" text NOT NULL,
    "Role" integer NOT NULL,
    "Age" integer NOT NULL,
    "Email" text NOT NULL,
    "Weight" real NOT NULL,
    "Height" real NOT NULL,
    "ConversationId" integer,
    CONSTRAINT "PK_Profiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Profiles_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES "Conversations" ("Id")
);

CREATE TABLE "Messages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Content" text NOT NULL,
    "DateSent" timestamp with time zone NOT NULL,
    "SenderId" integer NOT NULL,
    "ConversationId" integer,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES "Conversations" ("Id"),
    CONSTRAINT "FK_Messages_Profiles_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Profiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Posts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PublisherId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "PublicationType" integer NOT NULL,
    "Content" text NOT NULL,
    CONSTRAINT "PK_Posts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Posts_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Posts_Profiles_PublisherId" FOREIGN KEY ("PublisherId") REFERENCES "Profiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Sessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProfileId" integer NOT NULL,
    "Name" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Duration" interval NOT NULL,
    CONSTRAINT "PK_Sessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sessions_Profiles_ProfileId" FOREIGN KEY ("ProfileId") REFERENCES "Profiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Comments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PublishDate" timestamp with time zone NOT NULL,
    "PublisherId" integer NOT NULL,
    "Content" text NOT NULL,
    "CommentId" integer,
    "PostId" integer,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_Comments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "Comments" ("Id"),
    CONSTRAINT "FK_Comments_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id"),
    CONSTRAINT "FK_Comments_Profiles_PublisherId" FOREIGN KEY ("PublisherId") REFERENCES "Profiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Exercises" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Image" text NOT NULL,
    "CategoryId" integer NOT NULL,
    "SessionId" integer,
    CONSTRAINT "PK_Exercises" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Exercises_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Exercises_Sessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "Sessions" ("Id")
);

CREATE TABLE "Sets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Reps" integer NOT NULL,
    "Weight" real[] NOT NULL,
    "Rest" interval NOT NULL,
    "Mode" integer NOT NULL,
    "ExerciseId" integer,
    CONSTRAINT "PK_Sets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sets_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES "Exercises" ("Id")
);

CREATE INDEX "IX_Comments_CommentId" ON "Comments" ("CommentId");

CREATE INDEX "IX_Comments_PostId" ON "Comments" ("PostId");

CREATE INDEX "IX_Comments_PublisherId" ON "Comments" ("PublisherId");

CREATE INDEX "IX_Exercises_CategoryId" ON "Exercises" ("CategoryId");

CREATE INDEX "IX_Exercises_SessionId" ON "Exercises" ("SessionId");

CREATE INDEX "IX_Messages_ConversationId" ON "Messages" ("ConversationId");

CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");

CREATE INDEX "IX_Posts_CategoryId" ON "Posts" ("CategoryId");

CREATE INDEX "IX_Posts_PublisherId" ON "Posts" ("PublisherId");

CREATE INDEX "IX_Profiles_ConversationId" ON "Profiles" ("ConversationId");

CREATE INDEX "IX_Sessions_ProfileId" ON "Sessions" ("ProfileId");

CREATE INDEX "IX_Sets_ExerciseId" ON "Sets" ("ExerciseId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240112131619_Ath', '8.0.0');

COMMIT;